services:
  - type: web
    name: telegram-file-uploader
    env: python
    plan: free
    buildCommand: pip install -r requirements.txt
    startCommand: python main.py
    envVars:
      - key: TOKEN
        value: your_telegram_bot_token
